#!/bin/sh
if [ $OSTYPE = "linux-gnu" ]; then
    if [ -f /etc/redhat-release ]; then
        LSB_ID=`cat /etc/redhat-release | sed -e 's/release.*//'`
        LSB_VERSION=`cat /etc/redhat-release | sed -e 's/.*release//' | sed -e 's/[^0-9.]*//g'`
    else
        LSB_ID=`lsb_release -i | cut -f2 -d:`
        LSB_VERSION=`lsb_release -r | cut -f2 -d:`
    fi
    OS_VERSION=`echo $LSB_ID-$LSB_VERSION | sed -e "s/ //g"`
    MACHINE_TYPE=`uname -m`
    echo $OS_VERSION-$MACHINE_TYPE
else
    echo `uname -rsm | sed -e "s/ /-/g"`
fi
